# Generated by Buildr 1.4.17, change to your liking


# Version number for this release
VERSION_NUMBER = "0.5.0"
COPYRIGHT = "François Cabrol"

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"

desc "The Libjamu project"
define "libjamu" do

  project.version = VERSION_NUMBER
  manifest["Implementation-Vendor"] = COPYRIGHT
  compile # Add classpath dependencies
  # Select Java compiler version to 7
  compile.using :target=>'1.7'
  compile.options.lint = 'all' 

  # Generate a jar file
  package(:jar)

  # Generate the javadoc
  package :javadoc

end
